var age = 25;
age = 'ram';
age = true;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'luis' };
console.log(age);
var mixed = [];
mixed.push(2);
mixed.push('maria');
mixed.push(true);
console.log(mixed);
var ninja;
ninja = { name: 'roy', age: 20 };
ninja = { name: 20, age: 'roy' };
console.log(ninja);
